//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRequest
    {
        public System.DateTime RequestDate { get; set; }
        public string EquipmentName { get; set; }
        public string ProblemName { get; set; }
        public string UserFullName { get; set; }
        public string RequestDescription { get; set; }
        public string StatusName { get; set; }
        public int RequestMasterId { get; set; }
        public int RequestTime { get; set; }
        public string PriorityName { get; set; }
        public string StageName { get; set; }
        public string RequestComment { get; set; }
    }
}
